spring:
  application:
    name: juego_piedra_papel_tijera
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "root"
    password: "toor"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        jdbc:
          time_zone: "${TIME_ZONE:UTC}"
  flyway:
    enabled: "true"
    baseline-version: "1"
    schemas: "public"
    locations: "classpath:db/migration"
    sql-migration-prefix: "V"
    sql-migration-suffixes: ".sql"
    baseline-on-migrate: "true"
server:
  port: 8081

